#!/bin/bash
#
# quick_setup.sh - AmberTools25 + PMEMD24 Build and Installation Script
#
# This script automates the build and installation of AmberTools25 with PMEMD24
# into a conda environment. It includes fixes for various issues encountered
# during the build process.
#
# Usage:
#   ./quick_setup.sh [options]
#
# Options:
#   --source-dir PATH    Path to AmberTools25 source (default: ./repo/ambertools25_src)
#   --install-prefix PATH  Installation prefix (default: ./env)
#   --jobs N             Number of parallel jobs (default: auto-detect)
#   --skip-fixes         Skip applying source code fixes (use if already applied)
#   --clean              Clean build directory before building
#   --cuda               Enable CUDA/GPU support (default: enabled)
#   --no-cuda            Disable CUDA/GPU support
#   --cuda-path PATH     Path to CUDA toolkit (implies --cuda)
#   --setup-env          Create mamba environment and install MCP dependencies (default: enabled)
#   --no-setup-env       Skip mamba environment setup
#   --help               Show this help message
#
# Prerequisites:
#   - Conda environment with: cmake, gcc, gfortran, openmpi, netcdf, etc.
#   - AmberTools25 source code with PMEMD24 merged
#
# Author: Generated by Claude Code
# Date: 2026-01-20
#

set -e  # Exit on error

#==============================================================================
# Configuration
#==============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_DIR="${SCRIPT_DIR}/repo/ambertools25_src"
INSTALL_PREFIX="${SCRIPT_DIR}/env"
BUILD_DIR=""
JOBS=$(nproc 2>/dev/null || echo 4)
SKIP_FIXES=false
CLEAN_BUILD=false
ENABLE_CUDA=true
CUDA_PATH=""
SETUP_ENV=true

#==============================================================================
# Color output helpers
#==============================================================================

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_fix() {
    echo -e "${YELLOW}[FIX]${NC} $1"
}

#==============================================================================
# Parse command line arguments
#==============================================================================

parse_args() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            --source-dir)
                SOURCE_DIR="$2"
                shift 2
                ;;
            --install-prefix)
                INSTALL_PREFIX="$2"
                shift 2
                ;;
            --jobs)
                JOBS="$2"
                shift 2
                ;;
            --skip-fixes)
                SKIP_FIXES=true
                shift
                ;;
            --clean)
                CLEAN_BUILD=true
                shift
                ;;
            --cuda)
                ENABLE_CUDA=true
                shift
                ;;
            --no-cuda)
                ENABLE_CUDA=false
                shift
                ;;
            --cuda-path)
                CUDA_PATH="$2"
                ENABLE_CUDA=true
                shift 2
                ;;
            --setup-env)
                SETUP_ENV=true
                shift
                ;;
            --no-setup-env)
                SETUP_ENV=false
                shift
                ;;
            --help)
                show_help
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                show_help
                exit 1
                ;;
        esac
    done

    BUILD_DIR="${SOURCE_DIR}/build"

    # Auto-detect CUDA path if enabled but not specified
    if [[ "$ENABLE_CUDA" == true ]] && [[ -z "$CUDA_PATH" ]]; then
        if command -v nvcc &> /dev/null; then
            CUDA_PATH="$(dirname $(dirname $(which nvcc)))"
        elif [[ -d "/usr/local/cuda" ]]; then
            CUDA_PATH="/usr/local/cuda"
        else
            log_error "CUDA enabled but nvcc not found. Specify path with --cuda-path"
            exit 1
        fi
    fi
}

show_help() {
    head -30 "$0" | tail -25
}

#==============================================================================
# Prerequisite checks
#==============================================================================

check_prerequisites() {
    log_info "Checking prerequisites..."

    # Check source directory
    if [[ ! -d "$SOURCE_DIR" ]]; then
        log_error "Source directory not found: $SOURCE_DIR"
        exit 1
    fi

    # Check for CMakeLists.txt
    if [[ ! -f "$SOURCE_DIR/CMakeLists.txt" ]]; then
        log_error "CMakeLists.txt not found in source directory"
        exit 1
    fi

    # Check for required tools
    for cmd in cmake gcc g++ gfortran mpicc mpicxx mpifort python; do
        if ! command -v $cmd &> /dev/null; then
            log_error "Required command not found: $cmd"
            log_info "Please ensure your conda environment is activated"
            exit 1
        fi
    done

    log_success "All prerequisites satisfied"
}

#==============================================================================
# Setup mamba environment
#==============================================================================

setup_mamba_environment() {
    log_info "Setting up mamba environment at $INSTALL_PREFIX..."

    # Check if mamba is available
    if ! command -v mamba &> /dev/null; then
        log_error "mamba not found. Please install mamba first."
        log_info "You can install mamba with: conda install -c conda-forge mamba"
        exit 1
    fi

    # Remove existing environment if it exists
    if [[ -d "$INSTALL_PREFIX" ]]; then
        log_info "Removing existing environment at $INSTALL_PREFIX..."
        rm -rf "$INSTALL_PREFIX"
        log_success "Existing environment removed"
    fi

    # Create new environment
    log_info "Creating new mamba environment with Python 3.11..."
    mamba create -p "$INSTALL_PREFIX" python=3.11 -y

    if [[ $? -ne 0 ]]; then
        log_error "Failed to create mamba environment"
        exit 1
    fi
    log_success "Mamba environment created"

    # Activate the environment
    log_info "Activating environment..."
    eval "$(conda shell.bash hook)"
    conda activate "$INSTALL_PREFIX"

    if [[ $? -ne 0 ]]; then
        log_error "Failed to activate mamba environment"
        exit 1
    fi
    log_success "Environment activated"

    # Install MCP dependencies
    log_info "Installing MCP dependencies (fastmcp, loguru)..."
    pip install fastmcp loguru --ignore-installed --quiet

    if [[ $? -ne 0 ]]; then
        log_error "Failed to install MCP dependencies"
        exit 1
    fi
    log_success "MCP dependencies installed"

    # Install build dependencies for AmberTools
    log_info "Installing build dependencies for AmberTools..."
    mamba install -y \
        cmake \
        gcc \
        gxx \
        gfortran \
        openmpi \
        openmpi-mpicc \
        openmpi-mpicxx \
        openmpi-mpifort \
        netcdf-fortran \
        netcdf4 \
        boost \
        fftw \
        arpack \
        flex \
        bison \
        patch \
        make \
        2>&1 | tee mamba_install.log

    if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
        log_warning "Some mamba packages may have failed to install. Check mamba_install.log"
    fi

    log_success "Environment setup completed"
    echo ""
    log_info "Environment is ready. You may need to re-run this script without --setup-env to build AmberTools."
}

#==============================================================================
# FIX 1: benchmarks/CMakeLists.txt placeholder
#
# PROBLEM: The benchmarks/CMakeLists.txt file only contains a placeholder
# comment, causing CMake to fail when it tries to add_subdirectory(benchmarks).
#
# ERROR MESSAGE:
#   CMake Error at CMakeLists.txt:258 (add_subdirectory):
#     The source directory does not contain a CMakeLists.txt file.
#
# SOLUTION: Replace the placeholder with a minimal valid CMakeLists.txt
#==============================================================================

fix_benchmarks_cmake() {
    local file="$SOURCE_DIR/benchmarks/CMakeLists.txt"

    log_fix "Fixing benchmarks/CMakeLists.txt placeholder issue"

    if [[ -f "$file" ]]; then
        # Check if it's just a placeholder (less than 100 bytes typically means placeholder)
        local size=$(wc -c < "$file")
        if [[ $size -lt 100 ]]; then
            cat > "$file" << 'EOF'
# Benchmarks directory - placeholder for release builds
# This file was auto-generated to fix CMake configuration
cmake_minimum_required(VERSION 3.8)

# Benchmarks are not included in the standard distribution
# If you have benchmark files, add them here
EOF
            log_success "Fixed benchmarks/CMakeLists.txt"
        else
            log_info "benchmarks/CMakeLists.txt appears to already have content"
        fi
    else
        mkdir -p "$(dirname "$file")"
        cat > "$file" << 'EOF'
# Benchmarks directory - placeholder for release builds
cmake_minimum_required(VERSION 3.8)
EOF
        log_success "Created benchmarks/CMakeLists.txt"
    fi
}

#==============================================================================
# FIX 2: 3rdPartyTools.cmake - Missing xblas, arpack, fftw configuration
#
# PROBLEM: xblas, arpack, and fftw are listed in NEEDED_3RDPARTY_TOOLS and
# BUNDLED_3RDPARTY_TOOLS but don't have proper configuration entries in
# 3rdPartyTools.cmake.
#
# ERROR MESSAGES:
#   - /usr/bin/ld: cannot find -lxblas: No such file or directory
#   - undefined reference to `dsaupd_', `dseupd_', `dmout_' (ARPACK)
#   - FFTW_MPI_WORKS not found
#
# SOLUTION: Add proper configuration for these libraries
#==============================================================================

fix_3rdparty_tools() {
    local file="$SOURCE_DIR/cmake/3rdPartyTools.cmake"

    log_fix "Fixing 3rdPartyTools.cmake configuration"

    if [[ ! -f "$file" ]]; then
        log_error "3rdPartyTools.cmake not found"
        return 1
    fi

    # Backup original file
    cp "$file" "${file}.backup"

    # Check if xblas is already in 3RDPARTY_TOOLS list
    if ! grep -q "^set(3RDPARTY_TOOLS" "$file" || ! grep -A20 "^set(3RDPARTY_TOOLS" "$file" | grep -q "xblas"; then
        log_info "Adding xblas, arpack, fftw to 3RDPARTY_TOOLS list"

        # Find and replace the 3RDPARTY_TOOLS list
        sed -i 's/set(3RDPARTY_TOOLS/set(3RDPARTY_TOOLS\nxblas\narpack\nfftw/g' "$file" 2>/dev/null || true
    fi

    # Add NEED_arpack configuration if not present
    if ! grep -q "NEED_arpack" "$file"; then
        log_info "Adding NEED_arpack configuration"

        # Find a good insertion point (after NEED_fftw section or before first 3rdparty config)
        # We'll append to the file and let CMake handle the order
        cat >> "$file" << 'EOF'

#------------------------------------------------------------------------------
#  ARPACK (Added by quick_setup.sh)
#------------------------------------------------------------------------------

# Set NEED_arpack based on USE_ARPACK (defaults to TRUE for cpptraj)
if(NOT DEFINED NEED_arpack)
    if(NOT DEFINED USE_ARPACK OR USE_ARPACK)
        set(NEED_arpack TRUE)
    else()
        set(NEED_arpack FALSE)
    endif()
endif()
EOF
    fi

    # Add NEED_xblas configuration if not present
    if ! grep -q "NEED_xblas" "$file"; then
        log_info "Adding NEED_xblas configuration"

        cat >> "$file" << 'EOF'

#------------------------------------------------------------------------------
#  XBLAS (Added by quick_setup.sh)
#------------------------------------------------------------------------------

# Set NEED_xblas - required by RISM
if(NOT DEFINED NEED_xblas)
    set(NEED_xblas TRUE)
endif()

if(NEED_xblas)
    # XBLAS is always built internally as there's no external xblas finder
    set_3rdparty(xblas INTERNAL)
    list(APPEND 3RDPARTY_SUBDIRS xblas)
endif()
EOF
    fi

    # Add NEED_fftw configuration if not present
    if ! grep -q "NEED_fftw" "$file"; then
        log_info "Adding NEED_fftw configuration"

        cat >> "$file" << 'EOF'

#------------------------------------------------------------------------------
#  FFTW (Added by quick_setup.sh)
#------------------------------------------------------------------------------

# Set NEED_fftw - required by various tools
if(NOT DEFINED NEED_fftw)
    set(NEED_fftw TRUE)
endif()
EOF
    fi

    log_success "Fixed 3rdPartyTools.cmake"
}

#==============================================================================
# FIX 3: TFE GBSA amino acid variables not declared
#
# PROBLEM: Several Fortran files reference amino acid variables (ala, arg, asn,
# asp, cys, gln, glu, gly, his, hip, ile, leu, lys, met, phe, pro, ser, thr,
# triptophan, tyr, valine, bb) that are used in TFE GBSA mode but never declared.
#
# ERROR MESSAGE:
#   Error: Symbol 'ala' at (1) has no IMPLICIT type
#   Error: Symbol 'arg' at (1) has no IMPLICIT type
#   ... (similar for all amino acid variables)
#
# AFFECTED FILES:
#   - AmberTools/src/sander/egb.F90
#   - AmberTools/src/sander/mdread1.F90
#   - AmberTools/src/sander/mdread2.F90
#
# SOLUTION: Add _REAL_ declarations for these variables in each file
#==============================================================================

fix_tfe_gbsa_variables() {
    log_fix "Fixing TFE GBSA amino acid variable declarations"

    local sander_dir="$SOURCE_DIR/AmberTools/src/sander"

    # Declaration block to add
    local decl_block='   ! variables for TFE GBSA mode (amino acid residue surface tension corrections)
   ! NOTE: Added by quick_setup.sh to fix missing declarations
   _REAL_ :: ala=0.0d0, arg=0.0d0, asn=0.0d0, asp=0.0d0, cys=0.0d0, gln=0.0d0, glu=0.0d0, gly=0.0d0
   _REAL_ :: his=0.0d0, hip=0.0d0, ile=0.0d0, leu=0.0d0, lys=0.0d0, met=0.0d0, phe=0.0d0, pro=0.0d0
   _REAL_ :: ser=0.0d0, thr=0.0d0, triptophan=0.0d0, tyr=0.0d0, valine=0.0d0, bb=0.0d0'

    # Fix egb.F90
    local egb_file="$sander_dir/egb.F90"
    if [[ -f "$egb_file" ]] && ! grep -q "TFE GBSA mode" "$egb_file"; then
        log_info "Fixing $egb_file"
        cp "$egb_file" "${egb_file}.backup"

        # Insert after "integer ineighborpt" line
        sed -i '/integer ineighborpt/a\
\
   ! variables for TFE GBSA mode (amino acid residue surface tension corrections)\
   ! NOTE: Added by quick_setup.sh to fix missing declarations\
   _REAL_ :: ala=0.0d0, arg=0.0d0, asn=0.0d0, asp=0.0d0, cys=0.0d0, gln=0.0d0, glu=0.0d0, gly=0.0d0\
   _REAL_ :: his=0.0d0, hip=0.0d0, ile=0.0d0, leu=0.0d0, lys=0.0d0, met=0.0d0, phe=0.0d0, pro=0.0d0\
   _REAL_ :: ser=0.0d0, thr=0.0d0, triptophan=0.0d0, tyr=0.0d0, valine=0.0d0, bb=0.0d0' "$egb_file"

        log_success "Fixed egb.F90"
    else
        log_info "egb.F90 already fixed or not found"
    fi

    # Fix mdread1.F90
    local mdread1_file="$sander_dir/mdread1.F90"
    if [[ -f "$mdread1_file" ]] && ! grep -q "TFE GBSA mode" "$mdread1_file"; then
        log_info "Fixing $mdread1_file"
        cp "$mdread1_file" "${mdread1_file}.backup"

        # Insert after "_REAL_      timlim" line
        sed -i '/_REAL_.*timlim/a\
   ! variables for TFE GBSA mode (amino acid residue surface tension corrections)\
   _REAL_ :: ala=0.0d0, arg=0.0d0, asn=0.0d0, asp=0.0d0, cys=0.0d0, gln=0.0d0, glu=0.0d0, gly=0.0d0\
   _REAL_ :: his=0.0d0, hip=0.0d0, ile=0.0d0, leu=0.0d0, lys=0.0d0, met=0.0d0, phe=0.0d0, pro=0.0d0\
   _REAL_ :: ser=0.0d0, thr=0.0d0, triptophan=0.0d0, tyr=0.0d0, valine=0.0d0, bb=0.0d0' "$mdread1_file"

        log_success "Fixed mdread1.F90"
    else
        log_info "mdread1.F90 already fixed or not found"
    fi

    # Fix mdread2.F90
    local mdread2_file="$sander_dir/mdread2.F90"
    if [[ -f "$mdread2_file" ]] && ! grep -q "TFE GBSA mode" "$mdread2_file"; then
        log_info "Fixing $mdread2_file"
        cp "$mdread2_file" "${mdread2_file}.backup"

        # Insert after "_REAL_ emtmd" line
        sed -i '/_REAL_ emtmd/a\
   ! variables for TFE GBSA mode (amino acid residue surface tension corrections)\
   _REAL_ :: ala=0.0d0, arg=0.0d0, asn=0.0d0, asp=0.0d0, cys=0.0d0, gln=0.0d0, glu=0.0d0, gly=0.0d0\
   _REAL_ :: his=0.0d0, hip=0.0d0, ile=0.0d0, leu=0.0d0, lys=0.0d0, met=0.0d0, phe=0.0d0, pro=0.0d0\
   _REAL_ :: ser=0.0d0, thr=0.0d0, triptophan=0.0d0, tyr=0.0d0, valine=0.0d0, bb=0.0d0' "$mdread2_file"

        log_success "Fixed mdread2.F90"
    else
        log_info "mdread2.F90 already fixed or not found"
    fi
}

#==============================================================================
# FIX 4: amber.sh missing AMBERHOME export
#
# PROBLEM: The generated amber.sh script sets PMEMDHOME but not AMBERHOME.
# The wrapper scripts for tools like antechamber expect AMBERHOME to be set.
#
# ERROR MESSAGE:
#   /bin/wrapped_progs/antechamber: No such file or directory
#
# SOLUTION: This is fixed post-installation by adding AMBERHOME export
#==============================================================================

fix_amber_sh() {
    local amber_sh="$INSTALL_PREFIX/amber.sh"

    if [[ -f "$amber_sh" ]]; then
        log_fix "Fixing amber.sh to export AMBERHOME"

        if ! grep -q 'AMBERHOME' "$amber_sh"; then
            # Add AMBERHOME export after PMEMDHOME
            sed -i '/export PMEMDHOME=/a export AMBERHOME="$PMEMDHOME"' "$amber_sh"
            log_success "Fixed amber.sh"
        else
            log_info "amber.sh already has AMBERHOME"
        fi
    fi
}

#==============================================================================
# Apply all fixes
#==============================================================================

apply_all_fixes() {
    log_info "Applying source code fixes..."
    echo ""

    fix_benchmarks_cmake
    echo ""

    fix_3rdparty_tools
    echo ""

    fix_tfe_gbsa_variables
    echo ""

    log_success "All source code fixes applied"
}

#==============================================================================
# CMake configuration
#==============================================================================

run_cmake() {
    log_info "Running CMake configuration..."

    mkdir -p "$BUILD_DIR"
    cd "$BUILD_DIR"

    if [[ "$CLEAN_BUILD" == true ]]; then
        log_info "Cleaning build directory..."
        rm -rf CMakeCache.txt CMakeFiles
    fi

    # Set MPI environment for conda
    export OPAL_PREFIX="$INSTALL_PREFIX"

    # Build CUDA flags if enabled
    local CUDA_FLAGS=""
    if [[ "$ENABLE_CUDA" == true ]]; then
        log_info "CUDA enabled, using: $CUDA_PATH"
        CUDA_FLAGS="-DCUDA=ON -DCUDA_TOOLKIT_ROOT_DIR=$CUDA_PATH"

        # Detect GPU architecture for optimization
        if command -v nvidia-smi &> /dev/null; then
            local compute_cap=$(nvidia-smi --query-gpu=compute_cap --format=csv,noheader 2>/dev/null | head -1)
            if [[ -n "$compute_cap" ]]; then
                local arch="${compute_cap//./}"
                log_info "Detected GPU compute capability: $compute_cap (sm_$arch)"
                CUDA_FLAGS="$CUDA_FLAGS -DCUDA_NVCC_FLAGS=-gencode;arch=compute_${arch},code=sm_${arch}"
            fi
        fi
    fi

    cmake .. \
        -DCMAKE_INSTALL_PREFIX="$INSTALL_PREFIX" \
        -DCOMPILER=MANUAL \
        -DMPI=ON \
        $CUDA_FLAGS \
        -DBUILD_PYTHON=ON \
        -DDOWNLOAD_MINICONDA=OFF \
        -DPYTHON_EXECUTABLE="$(which python)" \
        -DCMAKE_C_COMPILER="$(which gcc)" \
        -DCMAKE_CXX_COMPILER="$(which g++)" \
        -DCMAKE_Fortran_COMPILER="$(which gfortran)" \
        -DMPI_C_COMPILER="$(which mpicc)" \
        -DMPI_CXX_COMPILER="$(which mpicxx)" \
        -DMPI_Fortran_COMPILER="$(which mpifort)" \
        -Wno-dev \
        2>&1 | tee cmake_output.log

    if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
        log_error "CMake configuration failed. Check cmake_output.log for details."
        exit 1
    fi

    log_success "CMake configuration completed"
}

#==============================================================================
# Build
#==============================================================================

run_build() {
    log_info "Building AmberTools25 + PMEMD24 with $JOBS parallel jobs..."

    cd "$BUILD_DIR"

    # Set MPI environment for conda
    export OPAL_PREFIX="$INSTALL_PREFIX"

    make -j"$JOBS" 2>&1 | tee build_output.log

    if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
        log_error "Build failed. Check build_output.log for details."
        exit 1
    fi

    log_success "Build completed successfully"
}

#==============================================================================
# Installation
#==============================================================================

run_install() {
    log_info "Installing to $INSTALL_PREFIX..."

    cd "$BUILD_DIR"

    make install 2>&1 | tee install_output.log

    if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
        log_error "Installation failed. Check install_output.log for details."
        exit 1
    fi

    # Fix amber.sh post-installation
    fix_amber_sh

    # Fix numpy compatibility for pdb4amber/parmed
    fix_numpy_compatibility

    log_success "Installation completed"
}

#==============================================================================
# FIX 5: numpy.compat module removed in numpy 2.x
#
# PROBLEM: pdb4amber depends on parmed, which uses numpy.compat that was
# removed in numpy 2.0+. This causes import errors when running pdb4amber.
#
# ERROR MESSAGE:
#   ModuleNotFoundError: No module named 'numpy.compat'
#
# SOLUTION: Downgrade numpy to version <2.0 (1.26.x)
#==============================================================================

fix_numpy_compatibility() {
    log_fix "Fixing numpy compatibility for pdb4amber/parmed"

    # Check if numpy 2.x is installed
    local numpy_version
    numpy_version=$(python -c "import numpy; print(numpy.__version__)" 2>/dev/null || echo "not installed")

    if [[ "$numpy_version" == "not installed" ]]; then
        log_info "numpy not installed, skipping"
        return
    fi

    local major_version="${numpy_version%%.*}"

    if [[ "$major_version" -ge 2 ]]; then
        log_info "numpy $numpy_version detected (>=2.0), downgrading for parmed compatibility..."
        python -m pip install 'numpy<2.0' --quiet 2>&1 || {
            log_warning "Failed to downgrade numpy, pdb4amber may not work"
            return
        }
        log_success "numpy downgraded to $(python -c 'import numpy; print(numpy.__version__)')"
    else
        log_info "numpy $numpy_version is compatible"
    fi
}

#==============================================================================
# Verification
#==============================================================================

verify_installation() {
    log_info "Verifying installation..."

    # Source the environment
    source "$INSTALL_PREFIX/amber.sh"
    export OPAL_PREFIX="$INSTALL_PREFIX"

    local all_ok=true

    # Check key executables
    local tools=("antechamber" "cpptraj" "pmemd" "pmemd.MPI" "sander" "sander.MPI" "tleap")

    for tool in "${tools[@]}"; do
        if command -v "$tool" &> /dev/null; then
            log_success "$tool: $(which $tool)"
        else
            log_error "$tool: NOT FOUND"
            all_ok=false
        fi
    done

    # Check CUDA executables if CUDA was enabled
    if [[ "$ENABLE_CUDA" == true ]]; then
        echo ""
        log_info "Checking CUDA executables..."
        local cuda_tools=("pmemd.cuda" "pmemd.cuda.MPI")

        for tool in "${cuda_tools[@]}"; do
            if [[ -f "$INSTALL_PREFIX/bin/$tool" ]]; then
                log_success "$tool: $INSTALL_PREFIX/bin/$tool"
            else
                log_warning "$tool: NOT FOUND (CUDA build may have failed)"
            fi
        done
    fi

    # Test antechamber
    echo ""
    log_info "Testing antechamber..."
    if antechamber -h 2>&1 | head -3 | grep -q "Usage"; then
        log_success "antechamber works"
    else
        log_warning "antechamber may have issues"
    fi

    # Test cpptraj
    log_info "Testing cpptraj..."
    if cpptraj --version 2>&1 | grep -q "CPPTRAJ"; then
        log_success "cpptraj works"
    else
        log_warning "cpptraj may have issues"
    fi

    # Test Python modules
    echo ""
    log_info "Testing Python modules..."
    if python -c "import pytraj; print(f'pytraj: {pytraj.__version__}')" 2>/dev/null; then
        log_success "pytraj works"
    else
        log_warning "pytraj not available"
    fi

    echo ""
    if [[ "$all_ok" == true ]]; then
        log_success "Verification completed - all tools available"
    else
        log_warning "Some tools may be missing"
    fi
}

#==============================================================================
# Print summary
#==============================================================================

print_summary() {
    echo ""
    echo "=============================================================================="
    echo "                     AmberTools25 + PMEMD24 Installation Summary"
    echo "=============================================================================="
    echo ""
    echo "Installation prefix: $INSTALL_PREFIX"
    echo ""
    echo "To use AmberTools, add the following to your shell:"
    echo ""
    echo "    source $INSTALL_PREFIX/amber.sh"
    echo "    export OPAL_PREFIX=$INSTALL_PREFIX  # For MPI tools"
    echo ""
    echo "Or add to your ~/.bashrc:"
    echo ""
    echo "    test -f $INSTALL_PREFIX/amber.sh && source $INSTALL_PREFIX/amber.sh"
    echo "    export OPAL_PREFIX=$INSTALL_PREFIX"
    echo ""
    echo "=============================================================================="
    echo ""
}

#==============================================================================
# Main
#==============================================================================

main() {
    echo ""
    echo "=============================================================================="
    echo "           AmberTools25 + PMEMD24 Quick Setup Script"
    echo "=============================================================================="
    echo ""

    parse_args "$@"

    log_info "Source directory: $SOURCE_DIR"
    log_info "Install prefix: $INSTALL_PREFIX"
    log_info "Build directory: $BUILD_DIR"
    log_info "Parallel jobs: $JOBS"
    echo ""

    # Setup mamba environment if requested
    if [[ "$SETUP_ENV" == true ]]; then
        setup_mamba_environment
        echo ""
        log_info "Environment setup complete. Continuing with build..."
        echo ""
    fi

    check_prerequisites
    echo ""

    if [[ "$SKIP_FIXES" != true ]]; then
        apply_all_fixes
        echo ""
    else
        log_info "Skipping source code fixes (--skip-fixes)"
        echo ""
    fi

    run_cmake
    echo ""

    run_build
    echo ""

    run_install
    echo ""

    verify_installation

    print_summary

    log_success "Setup completed successfully!"
}

# Run main function
main "$@"
